# Generated by Django 4.2.5 on 2023-10-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='react',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos'),
        ),
    ]
