# Generated by Django 4.2.5 on 2023-10-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0002_react_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos'),
        ),
    ]
